services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.backend
        ports:
            - 8000:8000
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        ports:
            - 8080:8080
